AWS how-to-guides EC2
devzero-inc/product-docs pull request #54
Opened 2024-07-22 06:23 UTC by garvit3835

2024-07-22 07:36 UTC, vikasgoswami2 commented
@mishushakov Please review this and let me know the feedback.

2024-07-23 10:47 UTC, mishushakov requested changes
looks good to me, only minor grammar fixes

2024-07-23 10:47 UTC, mishushakov commented on how-to-guides/cloud-services/aws/connect-to-an-ec2-instance.md
> +5. Choose **Instance type**.
the Instance type

2024-07-23 10:47 UTC, mishushakov commented on how-to-guides/cloud-services/aws/connect-to-an-ec2-instance.md
> +7. In **Network settings**, click on **edit** and choose the VPC where your bastion host is running, the private subnet and the security group which allows inbound access to VPC.
the Network settings, the VPC

2024-07-23 10:47 UTC, mishushakov commented on how-to-guides/cloud-services/aws/connect-to-an-ec2-instance.md
> +1. Go to **DevBox** and make a copy of the key pair.
the DevBox

2024-07-23 10:47 UTC, mishushakov commented on how-to-guides/cloud-services/aws/connect-to-an-ec2-instance.md
> +2. Connect to this EC2 using ssh and the new key pair:\
Connect to the desired EC2 instance

2024-07-23 13:56 UTC, vikasgoswami2 commented
@mishushakov please check now. I made the changes suggested by you.

2024-07-24 10:24 UTC, mishushakov approved these changes

2024-07-24 10:24 UTC, merged

2024-07-24 10:24 UTC, mishushakov commented
Perfect, thank you!