GCP how-to-guide MemoryStore
devzero-inc/product-docs pull request #84
Opened 2024-08-06 13:18 UTC by Sid-Lais

2024-08-06 23:33 UTC, dray92 commented on how-to-guides/cloud-services/gcp/connecting-to-memorystore.md
> +1. Go to **Memeorystore > Clusters**.
```suggestion
1. Go to **Memorystore > Clusters**.
```

2024-08-07 04:49 UTC, Sid-Lais commented on how-to-guides/cloud-services/gcp/connecting-to-memorystore.md
> +1. Go to **Memeorystore > Clusters**.
Fixed

2024-08-07 16:53 UTC, mishushakov requested changes
Grammatical

2024-08-09 17:09 UTC, dray92 commented
@Sid-Lais lint errors

2024-08-12 05:17 UTC, Sid-Lais commented
@dray92 Fixed errors

2024-08-12 08:57 UTC, merged